# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sportsterminal < Formula
  desc "Beautiful terminal interface for checking live sports scores"
  homepage "https://github.com/elliota43/sportsterminal"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elliota43/sportsterminal/releases/download/v1.2.0/sportsterminal_1.2.0_Darwin_x86_64.tar.gz"
      sha256 "8dc7e32db2403593da768dbe810af2fdad8846379dca1e2d452ee9a39b524cc2"

      def install
        bin.install "sportsterminal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elliota43/sportsterminal/releases/download/v1.2.0/sportsterminal_1.2.0_Darwin_arm64.tar.gz"
      sha256 "0a6d743230a54ee66abb4a9d52a0e6dcea032d7dacf38119a110f35d9c52c29d"

      def install
        bin.install "sportsterminal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliota43/sportsterminal/releases/download/v1.2.0/sportsterminal_1.2.0_Linux_x86_64.tar.gz"
      sha256 "a9eb9eb7ca0466827a62280d8c650923c27ab7d46ec7a92565d8986a4f2ecafe"
      def install
        bin.install "sportsterminal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliota43/sportsterminal/releases/download/v1.2.0/sportsterminal_1.2.0_Linux_arm64.tar.gz"
      sha256 "53a6a3f8343ab71f60c235d3c7b187a176c5f815e17e99f9ff40756e43504806"
      def install
        bin.install "sportsterminal"
      end
    end
  end

  test do
    system "#{bin}/sportsterminal", "--version"
  end
end
