# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sportsterminal < Formula
  desc "Beautiful terminal interface for checking live sports scores"
  homepage "https://github.com/elliota43/sportsterminal"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elliota43/sportsterminal/releases/download/v1.0.0/sportsterminal_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "77cbc3d96fa254f55b16700bb209366459206e3866482c25883376eb3972cd6d"

      def install
        bin.install "sportsterminal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elliota43/sportsterminal/releases/download/v1.0.0/sportsterminal_1.0.0_Darwin_arm64.tar.gz"
      sha256 "b3dc87238f7f6b37606e2c7b5d7cf5e86eef18c88f7b4a302c8cb5acdfe90245"

      def install
        bin.install "sportsterminal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliota43/sportsterminal/releases/download/v1.0.0/sportsterminal_1.0.0_Linux_x86_64.tar.gz"
      sha256 "b909a89d0c667412346e2ef3b048a67067855c2782087e8e2d1ad4e00bdce7cf"
      def install
        bin.install "sportsterminal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliota43/sportsterminal/releases/download/v1.0.0/sportsterminal_1.0.0_Linux_arm64.tar.gz"
      sha256 "977fffe8dc1d23e418dd61fb8b93ee09e3d1a1e88bde8520cda019208c22814e"
      def install
        bin.install "sportsterminal"
      end
    end
  end

  test do
    system "#{bin}/sportsterminal", "--version"
  end
end
