# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sportsterminal < Formula
  desc "Beautiful terminal interface for checking live sports scores"
  homepage "https://github.com/elliota43/sportsterminal"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elliota43/sportsterminal/releases/download/v1.1.0/sportsterminal_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "393e3c301b24bb66caba97ca6ee2e0a549bc9df9414b96bc316cfee648d98c53"

      def install
        bin.install "sportsterminal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elliota43/sportsterminal/releases/download/v1.1.0/sportsterminal_1.1.0_Darwin_arm64.tar.gz"
      sha256 "0d7b1b1d9a60b7ef175f5749ee79183e08ec46e7598108fdce5e9ce3c661e344"

      def install
        bin.install "sportsterminal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliota43/sportsterminal/releases/download/v1.1.0/sportsterminal_1.1.0_Linux_x86_64.tar.gz"
      sha256 "8c4eaf4508370119390bbae6b453b529cf7a08ef2d7a05f8528e2785d7bb7568"
      def install
        bin.install "sportsterminal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliota43/sportsterminal/releases/download/v1.1.0/sportsterminal_1.1.0_Linux_arm64.tar.gz"
      sha256 "61b45ffef5dec85708b6ceb1d59a6ff4f98c789f7fecb1f02e2f44d856f31a24"
      def install
        bin.install "sportsterminal"
      end
    end
  end

  test do
    system "#{bin}/sportsterminal", "--version"
  end
end
